title: DreamKnowSelf
description: A blog exploring philosophy, mysticism, astrology, and more.
url: "https://dreamknowself.com"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
