title: DreamKnowSelf
description: A blog exploring philosophy, mysticism, astrology, psychology, meditation, and spirituality
url: "https://dreamknowself.com"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

author:
  name: "Your Name"
  bio: "Exploring self-knowledge and awareness of dreams and reality"
  
minimal_mistakes_skin: "aqua"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
