title: DreamKnowSelf
description: A blog exploring philosophy, mysticism, astrology, and more.
url: "https://dreamknowself.com"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown